// Generated by LiveScript 1.6.0
(function(){
  var reg, wait, com, print, hoplon, z, l, R, p, bothNum, argE, typeE, add, hop, V, F1;
  reg = require("../dist/registry");
  require("../dist/main");
  wait = function(t, f){
    return setTimeout(f, t);
  };
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l, R = com.R;
  p = print.fail('test.js');
  bothNum = function(x, y){
    return typeof x === "number" && typeof y === "number";
  };
  argE = function(){
    return z("only accepts 2 arugument");
  };
  typeE = function(){
    return z("argument type has to be number");
  };
  add = function(x, y){
    return x + y;
  };
  hop = hoplon;
  V = hop.arma([1, 2], function(a, x){
    z(x);
    return "hello world";
  }).def();
  F1 = hop.whn(bothNum, typeE).arn(2, argE).ar(2, add).def(1);
  F1(1, 2);
}).call(this);
