// Generated by LiveScript 1.6.0
(function(){
  var reg, com, print, hoplon, z, l, p, bothNum, argE, typeE, add, hop, F;
  reg = require("../dist/registry");
  require("../dist/main");
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l;
  p = print.fail('test6.js');
  bothNum = function(x, y){
    return typeof x === "number" && typeof y === "number";
  };
  argE = function(){
    return z("only accepts 2 arugument");
  };
  typeE = function(){
    return z("argument type has to be number");
  };
  add = function(x, y){
    return x + y;
  };
  hop = hoplon;
  F = hop.arn([2, 3], function(){
    return 'fault';
  }).def('ok');
  F(1, 2, 3, 4);
}).call(this);
