// Generated by LiveScript 1.6.0
(function(){
  var reg, Benchmark, suite, wait, com, print, hoplon, z, l, R, betterTypeof, p, hop, type_num, type_str, V, A;
  reg = require("../dist/registry");
  require("../dist/main");
  Benchmark = require("benchmark");
  suite = new Benchmark.Suite;
  wait = function(t, f){
    return setTimeout(f, t);
  };
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l, R = com.R;
  betterTypeof = reg.betterTypeof;
  p = print.fail('test5.js');
  hop = hoplon;
  type_num = function(x){
    switch (x) {
    case 'integer':
      return 0;
    case 'boolean':
      return 1;
    default:
      return false;
    }
  };
  type_str = function(x){
    switch (x) {
    case 'string':
      return 3;
    default:
      return false;
    }
  };
  V = hop.ar(1, hop.ma(type_str, function(x){
    return x;
  }).def(4)).def(null);
  A = ['integer', 'boolean', 'bill', 'string', 'obama', 'arena'];
}).call(this);
