// Generated by LiveScript 1.6.0
(function(){
  var reg, wait, com, print, hoplon, z, l, R, p, bothNum, argE, typeE, add, hop, F1;
  reg = require("../dist/registry");
  require("../dist/main");
  wait = function(t, f){
    return setTimeout(f, t);
  };
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l, R = com.R;
  p = print.fail('test.js');
  bothNum = function(x, y){
    return typeof x === "number" && typeof y === "number";
  };
  argE = function(){
    return z("only accepts 2 arugument");
  };
  typeE = function(){
    return z("argument type has to be number");
  };
  add = function(x, y){
    return x + y;
  };
  hop = hoplon;
  F1 = hop.arma(1, function(){
    return false;
  }, function(){
    return 'hello-world';
  }).def('fault');
  F1('foo');
}).call(this);
