// Generated by LiveScript 1.6.0
(function(){
  var reg, com, print, hoplon, z, l, print_fail, p, bothNum, argE, typeE, add, hop;
  reg = require("../dist/registry");
  require("../dist/main");
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l, print_fail = com.print_fail;
  p = print_fail('test6.js');
  bothNum = function(x, y){
    return typeof x === "number" && typeof y === "number";
  };
  argE = function(){
    return z("only accepts 2 arugument");
  };
  typeE = function(){
    return z("argument type has to be number");
  };
  add = function(x, y){
    return x + y;
  };
  hop = hoplon;
}).call(this);
