// Generated by LiveScript 1.6.0
(function(){
  var reg, com, print, hoplon, z, l, print_fail, p, hop, V_inner, V_outer, ret;
  reg = require("../dist/registry");
  require("../dist/main");
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l, print_fail = com.print_fail;
  p = print_fail('test3.js');
  hop = hoplon.debug;
  V_inner = hop.wh(function(){
    return true;
  }, function(){
    return true;
  }).def();
  V_outer = hop.wh(function(){
    return true;
  }, V_inner).def(null);
  ret = V_outer([1, 2, 4], [1, 2, 4]);
  if (!ret) {
    p();
  }
}).call(this);
