// Generated by LiveScript 1.6.0
var reg, wait, com, print, hoplon, hop, z, l, R, c, print_fail;
reg = require("../dist/registry");
require("../dist/main");
wait = function(t, f){
  return setTimeout(f, t);
};
com = reg.com, print = reg.print, hoplon = reg.hoplon;
hop = hoplon;
z = com.z, l = com.l, R = com.R, c = com.c, print_fail = com.print_fail;