// Generated by LiveScript 1.6.0
(function(){
  var reg, com, print, hoplon, z, l, p, bothNum, argE, typeE, add2, hop, add;
  reg = require("../dist/registry");
  require("../dist/main");
  com = reg.com, print = reg.print, hoplon = reg.hoplon;
  z = com.z, l = com.l;
  p = print.fail('test7.js');
  bothNum = function(x, y){
    return typeof x === "number" && typeof y === "number";
  };
  argE = function(){
    return z("only accepts 2 arugument");
  };
  typeE = function(){
    return z("argument type has to be number");
  };
  add2 = function(x, y){
    return x + y;
  };
  hop = hoplon;
  add = hop.arwh(2, function(){
    return true;
  }, add2).def();
  z(add(1, 2));
}).call(this);
