var:
  proj: types
  which: test

watch: &watch
  - src
  - test/*/*.ls

ignore: &ignore
  - dist

rm.dist:
  description:
    - delete all .js files in dist folder.
  local: rm -rf dist/*/*

rm.src:
  description:
    - delete all .js files in src folder.
  local:
    rm src/*/*.js

gulpfile:
  watch: true
  description:
    - watch gulpfile.ls and run gulp default (only).
  local: &gulpfile
    - lsc -bco . src/gulpfile.ls
    - gulp default --silent

build:
  - gulp default --silent

test.all:
  watch: false
  description:
    - run all test files for all projects.
  local:
    - *gulpfile
    - |-
      for i in test/*/*.js
      do
        node $i || exit 1
        echo $i
      done
    - echo 'done!'

test.proj:
  watch: true
  description:
    - run all test files for proj=X.
  local:
    - *gulpfile
    - |-
      for i in test/${var.proj}/*.js
      do
        node $i || exit 1
      done

test.file:
  watch: true
  description:
    - run a specific test file for proj=X which=Y.
  local:
    - gulp default --silent
    - node ./test/${proj}/${which}.js || exit 1


dev.install:
  description: install all dev dependencies.
  local:
    - npm install gulp -g
    - pnpm install livescript
    - pnpm install gulp-tap
    - pnpm install gulp-livescript
    - pnpm install gulp-rename
    - pnpm install gulp-yaml
    - pnpm install gulp-replace
    - pnpm install gulp-util

version.update:
  watch: false
  local: update-version src/package.yaml hoplon version
